version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_URL=${APP_URL}
      - APP_FRONTEND_URL=${APP_FRONTEND_URL}
      - SALEOR_API_URL=${SALEOR_API_URL}
      - REDIS_URL=redis://redis:6379/0
      - SALEOR_APP_TOKEN=${SALEOR_APP_TOKEN}
    depends_on:
      - redis

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${APP_URL}
